language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build featurehub-admin-sdk.gemspec
  - gem install ./featurehub-admin-sdk-1.0.0.gem
