=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module FeaturehubAdminSdk
  class RolloutStrategyFieldType
    STRING = "STRING".freeze
    SEMANTIC_VERSION = "SEMANTIC_VERSION".freeze
    NUMBER = "NUMBER".freeze
    DATE = "DATE".freeze
    DATETIME = "DATETIME".freeze
    BOOLEAN = "BOOLEAN".freeze
    IP_ADDRESS = "IP_ADDRESS".freeze

    def self.all_vars
      @all_vars ||= [STRING, SEMANTIC_VERSION, NUMBER, DATE, DATETIME, BOOLEAN, IP_ADDRESS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if RolloutStrategyFieldType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #RolloutStrategyFieldType"
    end
  end
end
