=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module FeaturehubAdminSdk
  class RolloutStrategyAttributeConditional
    EQUALS = "EQUALS".freeze
    ENDS_WITH = "ENDS_WITH".freeze
    STARTS_WITH = "STARTS_WITH".freeze
    GREATER = "GREATER".freeze
    GREATER_EQUALS = "GREATER_EQUALS".freeze
    LESS = "LESS".freeze
    LESS_EQUALS = "LESS_EQUALS".freeze
    NOT_EQUALS = "NOT_EQUALS".freeze
    INCLUDES = "INCLUDES".freeze
    EXCLUDES = "EXCLUDES".freeze
    REGEX = "REGEX".freeze

    def self.all_vars
      @all_vars ||= [EQUALS, ENDS_WITH, STARTS_WITH, GREATER, GREATER_EQUALS, LESS, LESS_EQUALS, NOT_EQUALS, INCLUDES, EXCLUDES, REGEX].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if RolloutStrategyAttributeConditional.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #RolloutStrategyAttributeConditional"
    end
  end
end
