=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module FeaturehubAdminSdk
  class RolloutStrategyViolationType
    NO_NAME = "no_name".freeze
    NAME_TOO_LONG = "name_too_long".freeze
    EMPTY_MATCH_CRITERIA = "empty_match_criteria".freeze
    NEGATIVE_PERCENTAGE = "negative_percentage".freeze
    PERCENTAGE_OVER_100_PERCENT = "percentage_over_100_percent".freeze
    ARRAY_ATTRIBUTE_NO_VALUES = "array_attribute_no_values".freeze
    ATTR_INVALID_WELL_KNOWN_ENUM = "attr_invalid_well_known_enum".freeze
    ATTR_MISSING_VALUE = "attr_missing_value".freeze
    ATTR_MISSING_CONDITIONAL = "attr_missing_conditional".freeze
    ATTR_MISSING_FIELD_NAME = "attr_missing_field_name".freeze
    ATTR_MISSING_FIELD_TYPE = "attr_missing_field_type".freeze
    ATTR_VAL_NOT_SEMANTIC_VERSION = "attr_val_not_semantic_version".freeze
    ATTR_VAL_NOT_NUMBER = "attr_val_not_number".freeze
    ATTR_VAL_NOT_DATE = "attr_val_not_date".freeze
    ATTR_VAL_NOT_DATE_TIME = "attr_val_not_date_time".freeze
    ATTR_VAL_NOT_CIDR = "attr_val_not_cidr".freeze
    ATTR_UNKNOWN_FAILURE = "attr_unknown_failure".freeze

    def self.all_vars
      @all_vars ||= [NO_NAME, NAME_TOO_LONG, EMPTY_MATCH_CRITERIA, NEGATIVE_PERCENTAGE, PERCENTAGE_OVER_100_PERCENT, ARRAY_ATTRIBUTE_NO_VALUES, ATTR_INVALID_WELL_KNOWN_ENUM, ATTR_MISSING_VALUE, ATTR_MISSING_CONDITIONAL, ATTR_MISSING_FIELD_NAME, ATTR_MISSING_FIELD_TYPE, ATTR_VAL_NOT_SEMANTIC_VERSION, ATTR_VAL_NOT_NUMBER, ATTR_VAL_NOT_DATE, ATTR_VAL_NOT_DATE_TIME, ATTR_VAL_NOT_CIDR, ATTR_UNKNOWN_FAILURE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if RolloutStrategyViolationType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #RolloutStrategyViolationType"
    end
  end
end
