=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FeaturehubAdminSdk::ApplicationServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ApplicationServiceApi' do
  before do
    # run before each test
    @api_instance = FeaturehubAdminSdk::ApplicationServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ApplicationServiceApi' do
    it 'should create an instance of ApplicationServiceApi' do
      expect(@api_instance).to be_instance_of(FeaturehubAdminSdk::ApplicationServiceApi)
    end
  end

  # unit tests for create_application
  # Create a new application
  # @param id The id of the portfolio to find
  # @param application 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_environments Include the environments in the result
  # @option opts [Boolean] :include_features Include the features in the result
  # @return [Application]
  describe 'create_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_application
  # Delete an application
  # @param app_id The id of the application to find
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_environments Include the environments in the result
  # @return [Boolean]
  describe 'delete_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for find_applications
  # Gets a list of applications.
  # @param id The id of the portfolio to find
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_environments Include the environments in the result
  # @option opts [Boolean] :include_features Include the features in the result
  # @option opts [SortOrder] :order how to order the results
  # @option opts [String] :filter What to filter the results by
  # @return [Array<Application>]
  describe 'find_applications test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_application
  # Get application
  # @param app_id The id of the application to find
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_environments Include the environments in the result
  # @return [Application]
  describe 'get_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for summary_application
  # Geta summary of the application status
  # @param app_id The id of the application to find
  # @param [Hash] opts the optional parameters
  # @return [ApplicationSummary]
  describe 'summary_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_application
  # Update an application
  # @param app_id The id of the application to find
  # @param application 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_environments Include the environments in the result
  # @return [Application]
  describe 'update_application test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
