=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FeaturehubAdminSdk::CacheServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CacheServiceApi' do
  before do
    # run before each test
    @api_instance = FeaturehubAdminSdk::CacheServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CacheServiceApi' do
    it 'should create an instance of CacheServiceApi' do
      expect(@api_instance).to be_instance_of(FeaturehubAdminSdk::CacheServiceApi)
    end
  end

  # unit tests for cache_refresh
  # Allows superusers to refresh the global Dacha1 cache (if it exists).
  # @param cache_refresh_request 
  # @param [Hash] opts the optional parameters
  # @return [CacheRefreshResponse]
  describe 'cache_refresh test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
