=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FeaturehubAdminSdk::EnvironmentFeatureServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EnvironmentFeatureServiceApi' do
  before do
    # run before each test
    @api_instance = FeaturehubAdminSdk::EnvironmentFeatureServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EnvironmentFeatureServiceApi' do
    it 'should create an instance of EnvironmentFeatureServiceApi' do
      expect(@api_instance).to be_instance_of(FeaturehubAdminSdk::EnvironmentFeatureServiceApi)
    end
  end

  # unit tests for create_feature_for_environment
  # Create a specific feature in this environment.
  # @param eid The id of the environment to find features
  # @param key The key of the relevant feature
  # @param feature_value 
  # @param [Hash] opts the optional parameters
  # @return [FeatureValue]
  describe 'create_feature_for_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_feature_for_environment
  # No longer supported. Please update to a null value.
  # @param eid The id of the environment to find features
  # @param key The key of the relevant feature
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_feature_for_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_feature_for_environment
  # Update a specific feature in this environment.
  # @param eid The id of the environment to find features
  # @param key The key of the relevant feature
  # @param [Hash] opts the optional parameters
  # @return [FeatureValue]
  describe 'get_feature_for_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_features_for_environment
  # Get all features for this environment
  # @param eid The id of the environment to find features or &#39;latest&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_features include the features in the result
  # @option opts [String] :filter Filter the feature names by this filter.
  # @return [EnvironmentFeaturesResult]
  describe 'get_features_for_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_all_features_for_environment
  # Update all features for this environment that are passed. Ignores any other feature values that are not passed.
  # @param eid The id of the environment to find features or &#39;latest&#39;
  # @param feature_value 
  # @param [Hash] opts the optional parameters
  # @return [Array<FeatureValue>]
  describe 'update_all_features_for_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_feature_for_environment
  # Update a specific feature in this environment.
  # @param eid The id of the environment to find features
  # @param key The key of the relevant feature
  # @param feature_value 
  # @param [Hash] opts the optional parameters
  # @return [FeatureValue]
  describe 'update_feature_for_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
