=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FeaturehubAdminSdk::EnvironmentServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EnvironmentServiceApi' do
  before do
    # run before each test
    @api_instance = FeaturehubAdminSdk::EnvironmentServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EnvironmentServiceApi' do
    it 'should create an instance of EnvironmentServiceApi' do
      expect(@api_instance).to be_instance_of(FeaturehubAdminSdk::EnvironmentServiceApi)
    end
  end

  # unit tests for create_environment
  # Create a new environment
  # @param id The id of the application to find
  # @param environment 
  # @param [Hash] opts the optional parameters
  # @return [Environment]
  describe 'create_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_environment
  # Delete an environment
  # @param eid The id of the environment to find
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_acls Include the acls attached to this environment
  # @option opts [Boolean] :include_features Include the features attached to this environment
  # @option opts [Boolean] :include_details Include all environment details
  # @return [Boolean]
  describe 'delete_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for environment_ordering
  # this api is designed to update the ordering of environments. it will error on circular references or environments that don&#39;t exist.
  # @param id The id of the application to find
  # @param environment 
  # @param [Hash] opts the optional parameters
  # @return [Array<Environment>]
  describe 'environment_ordering test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for find_environments
  # Gets a list of environments.
  # @param id The id of the application to find
  # @param [Hash] opts the optional parameters
  # @option opts [EnvironmentSortOrder] :order how to order the results
  # @option opts [String] :filter What to filter the results by
  # @option opts [Boolean] :include_acls Include the acls attached to this environment
  # @option opts [Boolean] :include_features Include the features attached to this environment
  # @option opts [Boolean] :include_details Include all environment details
  # @return [Array<Environment>]
  describe 'find_environments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_environment
  # Get environment
  # @param eid The id of the environment to find
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_acls Include the acls attached to this environment
  # @option opts [Boolean] :include_features Include the features attached to this environment
  # @option opts [Boolean] :include_details Include all environment details
  # @option opts [Boolean] :include_sdk_url include the sdk url
  # @option opts [Boolean] :include_service_accounts Include the service accounts attached to this environment
  # @return [Environment]
  describe 'get_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_environment
  # Update an environment. Please use updateEnvironment2 as that has the fields that can actually be updated
  # @param eid The id of the environment to find
  # @param environment 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_acls Include the acls attached to this environment
  # @option opts [Boolean] :include_features Include the features attached to this environment
  # @option opts [Boolean] :include_details Include all environment details
  # @return [Environment]
  describe 'update_environment test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
