=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FeaturehubAdminSdk::InfoServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InfoServiceApi' do
  before do
    # run before each test
    @api_instance = FeaturehubAdminSdk::InfoServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InfoServiceApi' do
    it 'should create an instance of InfoServiceApi' do
      expect(@api_instance).to be_instance_of(FeaturehubAdminSdk::InfoServiceApi)
    end
  end

  # unit tests for get_info_version
  # Gets information as to what this server is.
  # @param [Hash] opts the optional parameters
  # @return [ApplicationVersionInfo]
  describe 'get_info_version test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
