=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FeaturehubAdminSdk::RolloutStrategyServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RolloutStrategyServiceApi' do
  before do
    # run before each test
    @api_instance = FeaturehubAdminSdk::RolloutStrategyServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RolloutStrategyServiceApi' do
    it 'should create an instance of RolloutStrategyServiceApi' do
      expect(@api_instance).to be_instance_of(FeaturehubAdminSdk::RolloutStrategyServiceApi)
    end
  end

  # unit tests for create_rollout_strategy
  # @param app_id The id of the application to find
  # @param rollout_strategy 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_who_changed include who changed
  # @return [RolloutStrategyInfo]
  describe 'create_rollout_strategy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_rollout_strategy
  # @param app_id The id of the application to find
  # @param strategy_id_or_name The id of the strategy or the unique name of it
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_who_changed include who changed
  # @return [RolloutStrategyInfo]
  describe 'delete_rollout_strategy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_rollout_strategy
  # @param app_id The id of the application to find
  # @param strategy_id_or_name The id of the strategy or the unique name of it
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_who_changed include who changed
  # @return [RolloutStrategyInfo]
  describe 'get_rollout_strategy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_application_rollout_strategies
  # @param app_id The id of the application to find
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_who_changed include who changed
  # @option opts [Boolean] :include_archived Include archived strategies
  # @return [Array<RolloutStrategyInfo>]
  describe 'list_application_rollout_strategies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_rollout_strategy
  # @param app_id The id of the application to find
  # @param strategy_id_or_name The id of the strategy or the unique name of it
  # @param rollout_strategy 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_who_changed include who changed
  # @return [RolloutStrategyInfo]
  describe 'update_rollout_strategy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for validate
  # Provide server validation responses for this group of rollout strategies
  # @param app_id The id of the application to find
  # @param rollout_strategy_validation_request 
  # @param [Hash] opts the optional parameters
  # @return [RolloutStrategyValidationResponse]
  describe 'validate test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
