=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FeaturehubAdminSdk::SetupServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SetupServiceApi' do
  before do
    # run before each test
    @api_instance = FeaturehubAdminSdk::SetupServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SetupServiceApi' do
    it 'should create an instance of SetupServiceApi' do
      expect(@api_instance).to be_instance_of(FeaturehubAdminSdk::SetupServiceApi)
    end
  end

  # unit tests for is_installed
  # Ping Feature Hub
  # @param [Hash] opts the optional parameters
  # @return [SetupResponse]
  describe 'is_installed test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for setup_site_admin
  # Setup site admin
  # @param setup_site_admin setupSiteAdmin
  # @param [Hash] opts the optional parameters
  # @return [TokenizedPerson]
  describe 'setup_site_admin test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
