=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FeaturehubAdminSdk::HiddenEnvironments
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FeaturehubAdminSdk::HiddenEnvironments do
  let(:instance) { FeaturehubAdminSdk::HiddenEnvironments.new }

  describe 'test an instance of HiddenEnvironments' do
    it 'should create an instance of HiddenEnvironments' do
      expect(instance).to be_instance_of(FeaturehubAdminSdk::HiddenEnvironments)
    end
  end
  describe 'test attribute "none_selected"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "environment_ids"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
