=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FeaturehubAdminSdk::StrategyAttributeWellKnownNames
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FeaturehubAdminSdk::StrategyAttributeWellKnownNames do
  let(:instance) { FeaturehubAdminSdk::StrategyAttributeWellKnownNames.new }

  describe 'test an instance of StrategyAttributeWellKnownNames' do
    it 'should create an instance of StrategyAttributeWellKnownNames' do
      expect(instance).to be_instance_of(FeaturehubAdminSdk::StrategyAttributeWellKnownNames)
    end
  end
end
