=begin
#ManagementResourceApi

#This describes the API clients use for accessing features. This reflects the API from 1.5.7 onwards.

The version of the OpenAPI document: 1.1.11

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FeaturehubAdminSdk::TokenizedPerson
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FeaturehubAdminSdk::TokenizedPerson do
  let(:instance) { FeaturehubAdminSdk::TokenizedPerson.new }

  describe 'test an instance of TokenizedPerson' do
    it 'should create an instance of TokenizedPerson' do
      expect(instance).to be_instance_of(FeaturehubAdminSdk::TokenizedPerson)
    end
  end
  describe 'test attribute "access_token"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "refresh_token"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "redirect_url"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "person"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
